name: odyssey_challenge_app
description: App developed for the Odyssey Challenge 2020 hackathon. 

version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  biometric_storage: 1.1.0+1
  bloc: ^6.1.0
  commercio_ui:
    git:
      url: https://github.com/commercionetwork/CommercioUI.git
      ref: master
  colorize_lumberdash: ^2.1.0
  cupertino_icons: ^1.0.0
  equatable: 1.2.5
  lumberdash: ^2.1.1
  print_lumberdash: 2.1.0
  qr_flutter: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.9.2
  mockito: ^4.1.3
  test_coverage: ^0.5.0

flutter:
  uses-material-design: true

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
          style: normal
        - asset: fonts/Lato-Italic.ttf
          style: italic
        - asset: fonts/Lato-Bold.ttf
          weight: 700

  assets:
    - document.txt
    - id_keys.json
